### ISSUE TITLE
[Feat] 메인페이지 구현

### ISSUE THREAD

**Issue by otcroz** [DS-Volare/front-end#13]
## ⚙️ 기능 설명

메인페이지 구현

## ✅ To-do

- [x] 페이지 디자인
- [x] framer-motion을 사용한 스크롤 3단 화면 전환 애니메이션
- [x] 메인페이지 인디케이터 구현, 화면 전환과 연결
- [x] 메인페이지 첫 번째 화면에 로고 적용

## 📑 참고 자료

- https://www.framer.com/motion/transition/
- [실무에 바로 적용 가능한 framer-motion](https://awesomelake.net/%EC%8B%A4%EB%AC%B4%EC%97%90-%EB%B0%94%EB%A1%9C-%EC%A0%81%EC%9A%A9-%EA%B0%80%EB%8A%A5%ED%95%9C-framer-motion/)

## Related issue
- #14
