### ISSUE TITLE
[Feat] 디자인 공통사항 적용

### ISSUE THREAD

**Issue by yellow-jam** [DS-Volare/front-end#2]
## ⚙️ 기능 설명

프로젝트 전체적으로 적용해야 할 디자인 요소

## ✅ To-do

- [x] @font-face, font-family 설정 (부크크명조)
[BookkMyungjo_Light.zip](https://github.com/user-attachments/files/15994979/BookkMyungjo_Light.zip)
[BookkMyungjo_Bold.zip](https://github.com/user-attachments/files/15994980/BookkMyungjo_Bold.zip)
- [x] fabicon 로고 설정
- [x] 웹페이지 title 설정

## 📑 참고 자료

- 
-
