### ISSUE TITLE
[Feat] 변환페이지 컴포넌트 애니메이션 구현

### ISSUE THREAD

**Issue by otcroz** [DS-Volare/front-end#23]
## ⚙️ 기능 설명

- 사용자가 서비스의 순서를 인식할 수 있도록 컴포넌트 간 애니메이션을 구현하려고 합니다.
- 또한, 사용자가 어떤 일을 수행하는지에 따라 애니메이션 적용
- 소설, 상호참조, 대본, 스토리보드, 통계 컴포넌트에 적용

## ✅ To-do

- [x] 인디케이터 바를 클릭했을 때 해당 컴포넌트로 이동하는 스크롤 애니메이션 구현
- [x] 상태, 컴포넌트 연결: 변환 페이지에서의 기능이 유기적으로 연결되도록 구현(애니메이션X)
- [x] 변환페이지 컴포넌트 간 애니메이션 구현
- [x] 애니메이션 후 컴포넌트의 위치가 인디케이터와 들어맞도록 반영하기

## 📑 참고 자료

- 
-
