### ISSUE TITLE
[Feat] 챗봇 api 연결 (Stomp)

### ISSUE THREAD

**Issue by yellow-jam** [DS-Volare/front-end#36]
## ⚙️ 기능 설명

챗봇 컴포넌트에 백엔드 api를 연결합니다.

## ✅ To-do

- [x] Message interface의 내용을 DB 엔터티에 맞춰 변경
- [x] stomp 관련 코드 작성: connect, subscribe, publish(send)
- [x] scriptId 가져오는 코드 작성 (context)

## 📑 참고 자료

-  https://velog.io/@rlawogks2468/React로-Stomp와-Socket을-이용한-채팅방-구현하기
- https://uiop5809.tistory.com/335 (위와 동일, context로 구현)
- https://github.com/CSID-DGU/2022-2-OSSProj-KKJ-5/tree/main
