### ISSUE TITLE
[Feat] 유저 관리 API 작성: 회원가입 및 로그인, 로그아웃, Refresh token 재발급

### ISSUE THREAD

**Issue by otcroz** [DS-Volare/front-end#37]
## ⚙️ 기능 설명

react-query를 통해 스프링부트 서버에서 구현한 로그인 및 회원가입 API를 연결합니다.

## ✅ To-do

- [x] 네이버 로그인 및 회원가입 API 연결
- [x] 구글 로그인 및 회원가입 API 연결
- [x] 유저 관리 custom hook 작성
- [x] 로그아웃, refresh token 발급 API 연결

## 📑 참고 자료

- https://velog.io/@chuu1019/Access-Token%EA%B3%BC-Refresh-Token%EC%9D%B4%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%B4%EA%B3%A0-%EC%99%9C-%ED%95%84%EC%9A%94%ED%95%A0%EA%B9%8C
- https://tansfil.tistory.com/59

**Comment by otcroz** [comment]
### 🚨 react-query 설치 후 QueryClient를 초기화하는 과정에 오류 발생
QueryClient를 초기화하는 과정에서 `cacheTime`에 빨간줄이 생기며 오류가 발생했다.
```ts
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 1000 * 60,
      cacheTime: 1000 * 60 * 5,
    },
  },
});
```

오류 원인을 살펴봤더니, 버전 업데이트를 하면서 `cacheTime`에 대한 옵션을 제거한 것이었다.
(`enabled`, `staleTime`, `refetchInterval`, `select` 등등의 옵션만 제공한다.)

참고자료: https://tanstack.com/query/latest/docs/framework/react/guides/important-defaults

**Comment by otcroz** [comment]
### 소셜계정 연결 오류
![image](https://github.com/user-attachments/assets/c74c91ab-ebbd-4d0b-8c33-938ec9104705)
소셜 계정을 연결하는 중에 CORS 오류가 발생했다. url의 프록시 설정을 인식하지 못하여 발생하는 오류인 것으로 파악했으며, url을 `로 감싸면 오류가 발생하는 것이었다.

수정 전 코드
```ts
      const result = await axios.get(`/spring/oauth/authorize${endpoint}`);
      const data = result.data;

```
수정 후 코드
```ts
      const url = '/spring/oauth/authorize' + endpoint;
      const result = await axios.get(url);
      const data = result.data;
```

수정 후 코드로 바꾸었더니 CORS 오류가 나지 않고 잘 실행된다.
