### ISSUE TITLE
[Idea] 변환 페이지에서 상태들을 관리하는 방법에 대한 고민

### ISSUE THREAD

**Issue by otcroz** [DS-Volare/front-end#44]
## ⚙️ 제안 배경

변환 페이지의 데이터 상태관리와 저장 API 연결에 대해 고민이에요.
소설, 대본, 스토리보드, 통계 데이터는 ConvertPage 하위 컴포넌트인 단계별 ~~Box.tsx에 state로 위치해요.
```js
<ConvertPage>
   <NovelBox />
   <ScriptBox />
   <StoryboardBox />
   <StatisticsBox />
</ConvertPage>
```

![image](https://github.com/user-attachments/assets/9cc63bf3-3f86-4c2f-aac5-9fb9480e1038)
 예로 들어, 사용자가 작성하던 소설을 저장하는 동작을 실행할 때, 저장할 수 있는 버튼은 인디케이터에 있는 저장 버튼, 다음 단계의 박스에 있는 등장인물 인식 버튼을 눌러야합니다. 

 소설 저장을 구현하기 위해 `ConvertIndicator`, `ScriptBox`에 저장할 데이터를 전달해야 하지만 데이터가 각 `~~.Box`에 각 데이터를 지역적으로 관리(state)합니다. 추후에 소설 뿐만 아니라 대본, 스토리보드 데이터를 저장할 때도 고려해야 합니다.

 그래서 지금 코드에서 저장 API를 연결하면 각 컴포넌트에 setState를 props로 보내는 복잡한 코드를 생산할 것이라고 판단했어요.

### 기존 코드에서 구현하게 되는 방식
 저장할 때 하위 컴포넌트(~.Box) -> 상위 컴포넌트(ConvertPage)로 데이터를 옮겨준 다음에 저장을 해야 하며 상위 컴포넌트로 옮겨주기 위해서 setState를 ConvertPage에 또 만들어줘야 합니다.
```jsx
 const ConvertPage = () => { 

 const [novel, setNovel] = useState("");

  const handleSave = () => { // 소설 저장 코드 }
   return(
     <>
     <ConvertIndicator handleSave={handleSave}> // props로 handleSave 함수를 보내준다.
     <NovelBox setNovel={setNovel} /> // setNovel 상태관리 함수를 보내줘야 한다.
     <ScriptBox handleSave={handleSave}/>  // props로 handleSave 함수를 보내준다.
     <StoryboardBox />
     <StatisticsBox />
     </>
    )
  }
// text에서 작성한거라 들여쓰기가 친절하지 않은 점 양해부탁드립니다.
```
소설 저장 코드를 위해 보내줘야 하는 props가 이정도라고 생각했습니다. 하지만 대본과 스토리보드를 저장하기 위해 얼마나 많은 props가 생길까라는 걱정이 들었습니다...

## 제안 사항
그래서 2가지 방안을 세웠습니다.

### 1. 소설, 대본, 스토리보드, 통계 데이터(또는 상태)를 ConvertPage에서 지역적으로 state를 관리하고 하위 컴포넌트의 props로 상태를 보낸다. 

기본적인 형태는 이렇습니다.
```jsx
 const ConvertPage = () => { 

// (상태의 type은 예시)
 const [novel, setNovel] = useState("");
 const [script, setScript] = useState("");
 const [storyboard, setStoryboard] = useState(""); 
 const [staticstist, setStaticstist] = useState(""); 

  const handleSave = () => { // 전체 저장 코드 }
  const handleNovelSave = () => { // 소설 저장 코드 }
  const handleStoryBoardSave = () => { // 스토리보드 저장 코드 }

   return(
     <>
     <ConvertIndicator handleSave={handleSave}> // props로 handleSave 함수를 보내준다.
     <NovelBox setNovel={setNovel} /> // setNovel 상태관리 함수를 보내줘야 한다.
     <ScriptBox setScript={setScript} handleNovelSave ={handleNovelSave }/>  // props로 handleSave 함수를 보내준다.
     <StoryboardBox  setStoryboard={setStoryboard}/>
     <StatisticsBox setStaticstist={setStaticstist}/>
     </>
    )
  }
```

### 2. Context API를 사용하여 상태(데이터)를 전역으로 선언한다.
전역적으로 상태를 관리하는 방법 중 하나를 제안했을 뿐입니다. 다른 방법을 제안해주셔도 됩니다.
```jsx
// 상태는 context로 관리

 const ConvertPage = () => { 
  const [novel, useNovel] = useContextNovel();
  const [script, setScript] = useContextScript();
  const [storyboard, setStoryboard] = useContextStoryboard(); 
  const [staticstist, setStaticstist] = useContextStaticstist(); 

  const handleSave = () => { // 전체 저장 코드 API } // novel, script, storyboard, staticstist 사용
  
   return(
     <> // 상태를 props로 전달해줄 필요 없음. context가 각각의 Box 컴포넌트에 선언됨.
     <ConvertIndicator > 
     <NovelBox />
     <ScriptBox />  
     <StoryboardBox  />
     <StatisticsBox />
     </>
    )
```

음.. 함수와 상태를 전역으로 남발하지 않기 위해서는 전역으로 선언해야 하는 기준을 확립해야 한다고 생각합니다.. 저의 경우는 재사용성이라고 생각했고, 변환 페이지에서 컴포넌트 간 상태들이 오고가는 코드보다는 전역으로 선언해서 관리하는 게 코드 가독성과 품질을 높인다고 봤습니다.

## ✅ To-do

- [x] 상태 관리 방법 결정
- [x] 결정한 방법 적용
- [x] 코드 동작 확인

## 📑 참고 자료

- [Recoil, 이제는 떠나 보낼 시간이다](https://medium.com/@clockclcok/recoil-%EC%9D%B4%EC%A0%9C%EB%8A%94-%EB%96%A0%EB%82%98-%EB%B3%B4%EB%82%BC-%EC%8B%9C%EA%B0%84%EC%9D%B4%EB%8B%A4-ff2c8674cdd5)
 => 최근 프로젝트에만 해도 Recoil을 적용했었는데 2024년에 사용률이 줄어들었다는 점이 인상적이었다. 트렌드는 빠르게 변화하고 그것에 맞춰가야 한다는 게. . 마치 서핑하기 적절한 파도가 올 때 뛰어들어야 하는 것 같다.

**Comment by otcroz** [comment]
빠른 시일 내에 개발을 하기 위해 **Context API**를 사용하는 것이 적합하다고 생각했습니다. 하지만 `Context`를 구독하는 모든 컴포넌트의 렌더링을 막기 위해 `useMemo`를 함께 사용하여 렌더링 문제를 막고자 합니다.

**Comment by otcroz** [comment]
소설 변환 ~ 대본 변환까지의 코드 동작이 확인되었습니다.
