### ISSUE TITLE
[Feat] 변환페이지: 소설, 대본 API 연결하기

### ISSUE THREAD

**Issue by otcroz** [DS-Volare/front-end#45]
## ⚙️ 기능 설명

변환 페이지의 소설, 대본 API를 연결합니다.

## ✅ To-do

- [x] 소설 API 연결
- [x] 대본 API 연결
- [x] API 동작 확인하기

## 📑 참고 자료

-
