### ISSUE TITLE
[Feat] 메인페이지 애니메이션 관리, use 커스텀 훅 만들기

### ISSUE THREAD

**Issue by otcroz** [DS-Volare/front-end#46]
## ⚙️ 기능 설명

현재 메인페이지에서 wheel 이벤트가 발생했을 때 애니메이션이 적용되도록 구현했습니다.
이때 사용되는 애니메이션이 다른 상태(page)에 의존적이라 이 부분을 수정해야 합니다.(**setState 넘기기** or 전역 선언)
메인페이지에서 사용하는 애니메이션을 다른 컴포넌트에서도 사용할 수 있도록 수정하려고 합니다.

- 관련 이슈: #13 

## ✅ To-do

- [x] 애니메이션 use 커스텀 훅 생성
- [x] 메인페이지, 인디케이터 적용
- [x] 애니메이션 적용 확인하기

## 📑 참고 자료

- 
-
