### ISSUE TITLE
[Feat] 변환 페이지에서 사용되는 상태들을 전역적으로 관리하기

### ISSUE THREAD

**Issue by otcroz** [DS-Volare/front-end#47]
## ⚙️ 기능 설명

context API + useMemo를 사용하여 전역적으로 상태를 관리할 수 있도록 합니다.
**08.15 16:45 update |** 우선은 context API로 구현 후 useMemo가 필요할 것 같으면 도입 예정. 

 현재는 변환 페이지에 있는 하위 컴포넌트들이 각각의 useState를 갖고 있는 상태입니다.
이러한 구조의 문제점은, '저장' 기능을 수행할 때 발생합니다.

 저장 버튼은 인디케이터 컴포넌트에 존재하기 때문에, 저장을 클릭했을 때 박스에 흩어진 상태들을 저장할 수 있어야 합니다.
지역적으로 상태를 관리해도 저장하는 방법은 있지만 props로 상태들을 전달해줘야 하기에 스파게티 코드를 생산할 수 있습니다.

 즉, 변환 페이지에서 관리되는 데이터들을 전역적인 상태로 관리하여 어떤 컴포넌트에서나 데이터에 접근할 수 있도록 하고 이로 인해 코드의 가독성과 품질을 높일 것으로 기대됩니다.

+등장인물, 대본, 스토리보드에 선언된 useState가 많았던 것으로 기억하고 있는데 걱정입니다.

- 관련 이슈: #44 

## ✅ To-do

- [x] 제목, 소설, 등장인물 박스에서 사용되는 데이터를 전역적으로 상태 관리
- [x] 대본, 스토리보드, 통계 박스에서 사용되는 데이터를 전역적으로 상태 관리
- [x] 데이터가 웹페이지에 잘 띄워지는지 확인

## 📑 참고 자료

- 
-
