### ISSUE TITLE
[Feat] 스피너 적용하기

### ISSUE THREAD

**Issue by otcroz** [DS-Volare/front-end#48]
## ⚙️ 기능 설명

사용자가 서비스를 사용하면서 기다려야 하는 구간에 스피너를 적용합니다.

## ✅ To-do

- [ ] 변환 페이지 - 등장인물 인식 버튼 클릭 시 스피너 띄우기
- [ ] 변환 페이지 - 대본 변환 버튼 클릭 시 스피너 띄우기
- [ ] 메인 페이지 - 데모 API 호출 시 스피너 띄우기 (서버 배포 이후)

## 📑 참고 자료

- https://www.davidhu.io/react-spinners/
