### ISSUE TITLE
[Feat] 모달(Modal), 토스트(Toast) 디자인 통일을 위한 코드 세팅 및 적용하기

### ISSUE THREAD

**Issue by otcroz** [DS-Volare/front-end#50]
## ⚙️ 기능 설명

웹 서비스의 여러 페이지에서 사용될 모달과 토스트의 디자인의 통일성을 지키고, 동일한 코드를 작성할 수 있을 가능성을 줄여 코드 품질을 유지하고자 합니다.

## ✅ To-do

- [x] react-modal 설치 확인, react-toastify 설치
   - [x] 유저가 로그아웃 할 때
   - [x] 저장하지 않고 뒤로가기 하려고 할 때
- [x] toast 디자인 통일, 코드 작성하기
   - [x] 로그인(성공, 실패)
   - [x] 로그아웃(성공, 실패)
   - [x] 스토리보드 생성 완료(성공, 실패)
   - [x] 변환 내용 저장(성공, 실패)
   - [x] 챗봇 플로팅 버튼이 떴을 때

## 📑 참고 자료

- https://fkhadra.github.io/react-toastify/remove-toast
-

**Comment by otcroz** [comment]
Toast를 어느 위치에 띄우는 것이 좋을지 고민입니다. >bottom-center로 임시 결정
![image](https://github.com/user-attachments/assets/cf326339-8a10-4d61-9235-be873f0c5d92)
