### ISSUE TITLE
[Feat] 통계 API, d3 라이브러리를 사용하여 변환정보 시각화, 등장인물 출연률 API 연결

### ISSUE THREAD

**Issue by otcroz** [DS-Volare/front-end#54]
## ⚙️ 기능 설명

장소, 시간 정보를 반환하는 통계 API를 연결하여 변환 정보를 마인드맵으로 보여줍니다.

## ✅ To-do

- [x] npm install d3, @types/d3, chart-js, react-chartjs-2
- [x] d3 적용하기, dummy data
- [x] 통계 API 연결하기
- [x] chart.js stack bar 적용하기
- [x] 등장인물 출연률 API 연결하기

## 📑 참고 자료

- https://observablehq.com/@shreshthmohan/force-directed-graph

**Comment by otcroz** [comment]
변환 정보 시각화
![image](https://github.com/user-attachments/assets/16a4b0c8-e089-48f5-9b67-7e858c9f8d3a)

**Comment by otcroz** [comment]
![image](https://github.com/user-attachments/assets/28e59ee2-b987-4e25-8a80-154ce3d6091a)
