### ISSUE TITLE
[Feat] 마이페이지 구현

### ISSUE THREAD

**Issue by otcroz** [DS-Volare/front-end#6]
## ⚙️ 기능 설명

서비스의 마이페이지를 구현합니다.

## ✅ To-do

- [x] 마이페이지 레이아웃 디자인
- [x] 목록 아이템 디자인
- [x] px 단위 vh, vw, rem으로 변환하기

## 📑 참고 자료

- blog) [‘~’ is not assignable to type 'IntrinsicAttributes' error](https://velog.io/@yena1025/is-not-assignable-to-type-IntrinsicAttributes-%EC%97%90%EB%9F%AC-%ED%95%B4%EA%B2%B0%ED%95%98%EA%B8%B0)
- 참고자료2
