### ISSUE TITLE
[Feat] 토큰 재발급 로직 구현하기

### ISSUE THREAD

**Issue by otcroz** [DS-Volare/front-end#65]
## ⚙️ 기능 설명

리프레시 토큰이 만료되었을시 사용자에게 재로그인을 유도하려고 합니다.
액세스 토큰이 만료되었을 때는 reissue를 호출하여 토큰을 재발급합니다.(사용자는 이 동작을 모르도록 구현합니다.)

## ✅ To-do

- [x] 토큰이 만료되었을 시 에러 핸들링
- [x] 토큰 만료시 띄울 모달 만들기
- [x] 토큰 만료시 띄우는 모달의 state를 전역 선언
- [x] 리프레시 토큰이 만료되었을시 모달을 띄우도록 구현하기
- [x] 액세스 토큰을 사용하는 API 통신 코드에 토큰 예외 처리하기
- [x] 액세스 토큰이 만료되었을 시, reissue를 호출하여 액세스 토큰이 재발급되기까지 에러를 띄우지 않고 데이터를 기다리도록 react-query 수정하기(403TOKEN 에러일 경우에만 해당 동작을 하도록 구현)
    - [x]  axios intercepter 적용하기
    - [x] token403, token404 error에 대해 에러 핸들링 실행하기
- [x] API 실행 확인

## 📑 참고 자료

- [타입스크립트에서 에러핸들링을 전문가처럼 처리하기](https://medium.com/@yujso66/%EB%B2%88%EC%97%AD-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%EC%97%90%EC%84%9C-%EC%A0%84%EB%AC%B8%EA%B0%80%EC%B2%98%EB%9F%BC-%EC%97%90%EB%9F%AC-%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0-39d14f5cc6a2)
- [타입스크립트에서 커스텀 에러 처리하기](https://inpa.tistory.com/entry/TS-%F0%9F%93%98-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%EC%BB%A4%EC%8A%A4%ED%85%80-Error-%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0)
- [axios interceper 적용하기](https://leeseong010.tistory.com/133)

**Comment by otcroz** [comment]
### 토큰 만료 모달을 App.tsx에 선언한 이유
- 모달은 토큰이 만료될 때 띄워집니다. 즉, 어떤 페이지에서 토큰이 만료되는 오류가 발생할지 모릅니다. 
- 즉, 최상위 컴포넌트인 `App.tsx`에 모달을 선언하여 모달 state를 관리하는 것이 좋겠다는 판단입니다.

**Comment by otcroz** [comment]
## Axios intercepter 사용한 이유
- API에서 오류 발생하면 `catch(err)`문으로 이동한다. `catch(err)`문에서 토큰을 재발급하는 코드를 작성해야 하는데, 모든 API의 catch(err) 문에 토큰 재발급 코드를 작성 + API 재호출하는 코드를 작성하는 건 코드 가독성을 떨어뜨릴 뿐더러, 내가 용납할 수 없었다.
- Axios intercepter에서 오류가 발생했을 때, intercepter을 적용한 `axios` 객체에 대해서 공통으로 적용할 수 있으며, 에러핸들링을 다른 파일에서 관리하는 게 좋다.
- 덤으로 `header` 설정도 axios intercepter를 통해 적용했다. 각 API마다 `header`를 선언하고 API 호출 시 넣어서 보내주지 않아도 된다.

### Axios를 useHook으로 만든 이유
- useHook으로 만들지 않으면 usehook을 선언하지 못한다..

## 주요 코드 살펴보기
`useAxiosInstance.tsx`에서 createAciosInstance()를 보겠습니다.

### 요청 시 실행하는 코드
```js
    axiosInstance.interceptors.request.use(
      (config) => {
        if (accessToken && config.headers) {
          const { accessToken } = getTokenUser();
          config.headers['X-AUTH-TOKEN'] = accessToken; // 액세스 토큰 설정
        }

        return config;
      },
      (err) => {
        return Promise.reject(err);
      }
    );
```
axios를 사용하여 API를 호출하기 전! 이 코드로 이동하여 header를 설정하는 코드입니다.
흐름은 `axios.get('/api')` 코드 실행 → `intercepter.request.use` 호출 → API 요청
만약 이 과정에서 에러가 발생하면 err를 반환합니다.

### 반환 시 실행하는 코드
반환 시에는 `intercepter.request.use` 호출 → API 응답의 흐름으로 동작합니다.
```js
    axiosInstance.interceptors.response.use(
      (response) => {
        return response; // success
      },
```
API가 에러가 발생하지 않고 잘 실행되었다면 respnse를 그대로 반환합니다.
하지만 오류가 발생한다면? 제가 작성한 아래의 긴 코드가 실행됩니다.
```js
      async (err: unknown) => {
        // error
        if (err instanceof AxiosError) {
          const originRequest = err.config as CustomAxiosRequestConfig; // 직전에 실행한 요청

          if (
            originRequest && 
            err.response?.data.error.code == 'TOKEN403' && // 액세스 토큰 만료 오류인지 확인
            !originRequest._retry // API를 재호출했는지 확인
          ) {
            try {
              const result = await reissue(); // 토큰 재발급, result(boolean) 사용
              if (!result) { // 토큰재발급 실패로 간주
                return Promise.resolve({
                  data: {
                    result: {
                      isSuccess: false,
                      message: '토큰 재발급 실패',
                    },
                  },
                });
              } else if (originRequest.headers) {
                const { accessToken } = getTokenUser();
                originRequest.headers['X-AUTH-TOKEN'] = accessToken; // 헤더 적용
              }
              originRequest._retry = true; // 1번 재호출함을 표시. 
              try {
                const newResult = await axiosInstance.request(originRequest); // 요청 재시도
                return newResult; // 응답
              } catch (retryError) {
                return Promise.reject(retryError);
              }
            } catch (err) {
              console.log(err);
              return Promise.reject(err);
            }
          }
        }
      }
```

코드는 복잡해 보이지만 간단합니다. TOKEN403 오류인지 확인 → 토큰 재발급 API 호출 → API 호출 재시도
1. TOKEN403 오류인지 확인
originRequest는 이전에 실행했던 API의 config 정보를 가져옵니다. header가 안에 포함되어 있습니다.
그리고 조건문을 거칩니다.
```js
        if (err instanceof AxiosError) {
          const originRequest = err.config as CustomAxiosRequestConfig; // 직전에 실행한 요청

          if (
            originRequest && // 이전에 요청한 적 있는지
            err.response?.data.error.code == 'TOKEN403' && // 액세스 토큰 만료 오류인지 확인
            !originRequest._retry // API를 재호출했는지 확인
          ) {
```
3. 토큰 재발급 API 호출
3개의 조건을 만족해서 if문 안에 들어가게 되면 아래 코드를 실행합니다.
토큰을 재발급(reissue)하는 코드이고, 토큰 재발급에 실패하면 false를 반환하도록 구현했습니다.
 - 참고로 reissue 코드는 `createAxiosInstanceTwoTkn` 인스턴스를 사용합니다. API 호출시 2개의 토큰이 필요해서 구분했어요.
그리고 API를 반복적으로 호출하여 재귀가 만들어지지 않도록 originRequest._retry를 설정했습니다. 타입스크립트에서는 지원하지 않는다고 해서 타입을 선언하여 만들어줬습니다.
```js
            try {
              const result = await reissue(); // 토큰 재발급, result(boolean) 사용
              if (!result) { // 토큰재발급 실패로 간주
                return Promise.resolve({
                  data: {
                    result: {
                      isSuccess: false,
                      message: '토큰 재발급 실패',
                    },
                  },
                });
              } else if (originRequest.headers) {
                const { accessToken } = getTokenUser();
                originRequest.headers['X-AUTH-TOKEN'] = accessToken; // 헤더 적용
              }
              originRequest._retry = true; // 1번 재호출함을 표시. 
```
5. 토큰 재발급 후 헤더에 적용하고 API 호출 재시도
그리고 API를 재실행하면 끝! 
```js
            try {
                const newResult = await axiosInstance.request(originRequest); // 요청 재시도
                return newResult; // 응답
              } catch (retryError) {
                return Promise.reject(retryError);
              }
```

## 정리
그럼 정리해보자면,,
```js
// 1. useAuth.js: axios를 사용하여 요청하려고 합니다. 제가 intercepter를 위해 axios 인스턴스를 만들었어요.
const result = await axiosInstance.get(`/spring/users`); // 유저 정보 API 호출

// 2. useAxiosInstance.ts
axiosInstance.interceptors.request.use( 

// 3. 백엔드 서버는 요청을 받고 ~~ 응답을 줍니다.

// 4. useAxiosInstance.ts
axiosInstance.interceptors.response.use(

// 5. useAuth.js: 응답을 받습니다.
      const result = await axiosInstance.get(`/spring/users`);
      console.log('result: ', result);
      const data = result.data.result;
```
