### ISSUE TITLE
[Feat] 변환 페이지 디자인

### ISSUE THREAD

**Issue by otcroz** [DS-Volare/front-end#7]
## ⚙️ 기능 설명

변환페이지 레이아웃 디자인을 담당했습니다.

## ✅ To-do

- [x] 변환페이지 레이아웃 디자인
- [x] 제목 입력창, 인디케이터 컴포넌트 디자인
- [x] px 단위를 vw, vh, rem으로 변경하기
- [ ] media 적용하기: max-width에 따른 input과 인디케이터 레이아웃 조

## 📑 참고 자료

- https://developer.mozilla.org/ko/docs/Web/CSS/@media
-
